name: Deploy GitHub Infofnato

on:
  push:
    branches:
      - main  # ou a branch que você estiver usando para publicar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Construir site (se estiver usando gerador tipo eleventy ou similar)
        run: npm run build

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site  # ajuste se o diretório de saída for diferente
