image: python:3.8.13-buster

.join_script:
  before_script:
    - git config --global http.sslVerify "false"
    - apt-get update
    - apt-get install minify
    - pip install mkdocs mkdocs-material pymdown-extensions pipenv
    - pipenv lock
    - pipenv install --deploy

stages:
  - validation
  - deploy

validation:
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
  stage: validation
  extends:
    - .join_script
  script:
    - pipenv run mkdocs build --site-dir test

build:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  stage: deploy
  extends:
    - .join_script
  script:
    - pipenv run mkdocs build --site-dir public
  artifacts:
    paths:
      - public
    expire_in: 1 week

deploy:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  stage: deploy
  image: docker-hub.artifactory.globoi.com/tsuru/client:latest
  script:
    - tsuru app deploy -a iwiki public/
  needs:
    - job: build
    